### ISSUE TITLE
walkthrough 2, step 1

### ISSUE THREAD

**Issue by rbaumgar** [integr8ly/tutorial-web-app-walkthroughs#50] opened 2019-03-21 13:33 UTC
when source is created at Github and deployed:

Project already exists! When I delete project by hand, deployment continues, but project is not owed by the user! In my case I use evals02.

would be nice to have a way to skip this step - no repository created in Github, use a default repository.

**Comment by pwright** [comment] 2019-03-22 15:07
thanks for feedback. I'm not sure I understand, is the issue that the github project already exists, or that an OpenShift project already exists?

**Comment by rbaumgar** [comment] 2019-03-24 20:00
Launcher did
- create repo on Github
- upload source to Github
- create OpenShift project -- fail, project already exists...

**Comment by pwright** [comment] 2019-03-25 11:21
@david-martin any thoughts on this?

**Comment by david-martin** [comment] 2019-03-25 12:22
I'm not quite sure exactly what the problem is.
I am able to successfully create a launcher booster when the project already exists in OpenShift.
It sounds like there may be some permissions issue with who has access to your project @rbaumgar, but without steps to reproduce I'm at a loss.

Maybe this problem is better discussed (and could be better understood) in https://github.com/fabric8-launcher ?

**Comment by rbaumgar** [comment] 2019-03-25 12:25
I requested a cluster from RHPDS(integr8ly included) and then I started the walkthrough 2 and failed at laucher...

**Comment by pwright** [comment] 2019-04-02 14:43
closing, cannot reproduce, @rbaumgar reopen if you feel there is something we can do

**Closed as completed by pwright** 2019-04-02 14:43 UTC
